%import common.INT
%import common.ESCAPED_STRING
%import common.SIGNED_NUMBER -> NUMBER
%import common.NEWLINE -> NL
%import common.WS

// Circuit declaration
?circuit: (subcircuit | instance | model | directive)+

// Raw SPICE directive
directive: directive_name
directive_name: /[a-z][a-zA-Z0-9!${}_]+/

//directive_params: param_value (SEP param_value)*

// ?value: NUMBER | NAME | ESCAPED_STRING
//         | "[" value (" " value)* "]" -> value_list
// param_value: NAME "=" value | value
//param_value: value ["=" value]

// Component instance
instance: "instance"
// node: NAME | NUMBER
// nodes: "(" node (" " node)* ")"
// instance_params: ((" " | "\\") param_value)*
// instance_id: /[A-Z][0-9]+/
// %override INSTANCE: instance_id nodes NAME instance_params

// Subcircuit
subcircuit: "subcircuit"
// subcircuit_nodes: (NAME (" " NAME)*)
// subcircuit_params: "parameters" (param_value (" " param_value)*)
// subcircuit.3: "subckt" NAME subcircuit_nodes [subcircuit_params] (instance)* "ends" NAME

value: NUMBER

// Model declaration
model: "model" NAME NAME

NAME: /[a-zA-Z0-9!${}_]+/

SEP: (WS | "\\" | "+")
%ignore SEP

// SPICE comments
COMMENT: /\/\/[^\n]*/
%ignore COMMENT